# Data Underastandig

In [2]:
# import libs
import pandas as pd
import numpy as np

In [3]:
# import dataset

df_orders = pd.read_csv('../data/raw/olist_orders_dataset.csv')
df_order_items = pd.read_csv('../data/raw/olist_order_items_dataset.csv')
df_customers = pd.read_csv('../data/raw/olist_customers_dataset.csv')
df_payments = pd.read_csv('../data/raw/olist_order_payments_dataset.csv')
df_products = pd.read_csv('../data/raw/olist_products_dataset.csv')
df_translation = pd.read_csv('../data/raw/product_category_name_translation.csv')
df_geolocation = pd.read_csv('../data/raw/olist_geolocation_dataset.csv')
df_reviews = pd.read_csv('../data/raw/olist_order_reviews_dataset.csv')
df_sellers = pd.read_csv('../data/raw/olist_sellers_dataset.csv')

## orders table

In [4]:
df_orders.sample(n=5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
76407,8261284307e7712ea0491f342df56d74,ac2c4cb05aafb79b46c1b5e7e951bf69,delivered,2017-11-20 11:27:28,2017-11-20 11:35:24,2017-11-21 18:59:34,2017-11-30 11:39:48,2017-12-12 00:00:00
97412,e218234621ce56589ca6157a7cf827ac,5d5d1ea621e982d29cf41b788ba83f64,delivered,2017-09-14 09:41:36,2017-09-14 09:55:24,2017-09-18 21:49:49,2017-09-20 19:02:27,2017-09-29 00:00:00
45537,0726665518da3a4e1b9efff4de0089fc,0a663660b4e386d4cdc7f69376912e1e,delivered,2017-06-01 10:41:56,2017-06-01 10:55:14,2017-06-02 11:54:49,2017-06-06 14:17:30,2017-06-14 00:00:00
65463,845b246277d6bf2be20db34577513537,4ff8e39c2ab4a5985c6b772934e2ee3c,delivered,2017-10-28 14:28:53,2017-10-28 14:45:31,2017-10-31 16:02:07,2017-11-03 15:03:09,2017-11-17 00:00:00
9791,4e64cd773156febbf0e105d0b4aeaad0,2a6380a3c3cfcc8fc84783942f7c5ada,delivered,2018-03-16 00:21:49,2018-03-16 01:55:25,2018-03-29 20:33:22,2018-04-03 04:20:57,2018-04-13 00:00:00

In [5]:
df_orders.info()

print("\ncolumns 5 to 7 are date but thire Dtype is Object. should be change in EDA\n")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

columns 5 to 7 are date but thire Dtype is Object. should be change in EDA

In [6]:
print(df_orders.isnull().sum())

print("\n\ncolumns\norder_approved_at\n" \
      "order_delivered_carrier_date\n" \
      "order_delivered_customer_date\n" \
      "have missing value, Missing values may represent orders that have not yet reached that stage")

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64


columns
order_approved_at
order_delivered_carrier_date
order_delivered_customer_date
have missing value, Missing values may represent orders that have not yet reached that stage

In [7]:
# each order is registered only once
orders_dup = df_orders.order_id.duplicated().sum()
print(f"\nnum of orders_id duplicated: {orders_dup}\n\
    order id don't have null or duplicated value and based on a dataset logical is Primary Key")

# # This customer ID is not duplicated because it creates a new customer ID with each order
customer_dup = df_orders.customer_id.duplicated().sum()
print(f"\nnum of customer id duplicated: {customer_dup}\n")

order_counts = df_orders['order_status'].value_counts()
print(order_counts)

num of orders_id duplicated: 0
    order id don't have null or duplicated value and based on a dataset logical is Primary Key

num of customer id duplicated: 0

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

## order_items table

In [8]:
df_order_items.sample(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
80796,b7bad41b595c73cedf79fe679bf246d9,1,8747974bad06af6fbf0f2acf33a55ddc,612170e34b97004b3ba37eae81836b4c,2018-07-24 17:43:59,84.90,19.50
18322,2a16183656d9858dd244568f629e8c13,1,c6bf8cc852eee5c4ab264e792a9c23a1,5dceca129747e92ff8ef7a997dc4f8ca,2017-05-02 21:36:57,14.00,16.05
90928,ce89a61d7fb824d1eb7e05915b912a65,2,c1488892604e4ba5cff5b4eb4d595400,1554a68530182680ad5c8b042c3ab563,2017-05-18 22:05:15,38.50,35.67
49644,70cd45f4715c8840b197efee2b9d533c,1,e16045eef2ff02ee2a6469e167958bb0,c6381d2d013342748761e906d45aff76,2017-11-10 00:05:57,67.99,16.68
81918,ba35aab992c4504d63730c89ccc35613,3,0d85c435fd60b277ffb9e9b0f88f927a,f457c46070d02cadd8a68551231220dd,2018-02-26 07:27:28,68.90,16.92

In [9]:
df_order_items.info()

print("\ncolumn shipping_limit_date is date type but  Dtype is Object")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

column shipping_limit_date is date type but  Dtype is Object

In [10]:
# don't exist null values in order items
print(df_order_items.isnull().sum())

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [11]:
df_order_items[['freight_value', 'price']].agg(['min', 'max'])

# Some order items have a freight_value of 0.0. This should be 
# investigated during the EDA phase to determine whether
# it represents free shipping, promotional offers, or another rule ?

     freight_value    price
min           0.00     0.85
max         409.68  6735.00

## customers table

In [12]:
df_customers.sample(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
73055,7298e5225a74b55598d1030f959ba77d,2ada850dbe866246a92524d882e166d5,24350,niteroi,RJ
95206,4a6ca65e203304ab05746357bc7b61e7,7aaa326690fdfbb1086e6b6cf4a6206a,4290,sao paulo,SP
63506,72b02f1dedfa93df34149345e67bd4f8,a919e8959e6f20eb7dd8a9cfa6c2f6de,94175,gravatai,RS
88110,f90c0b67909aef5401de1537c2ccac12,a83e6fd03af88166652ef55ec13cbe85,48330,rio real,BA
96456,11a5f3092fc00cabdee343a56943d40b,c491d53abe7583f1d46046916ea6b01d,13020,campinas,SP

In [13]:
df_customers.info()

print("\ncount of null values")
print(df_customers.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

count of null values
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [14]:
df_customers.describe(include='object')

,customer_id,customer_unique_id,customer_city,customer_state
count,99441,99441,99441,99441
unique,99441,96096,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,sao paulo,SP
freq,1,17,15540,41746

In [15]:
customer_unique_id_dup = df_customers['customer_unique_id'].duplicated().sum()
customer_id_dup = df_customers['customer_id'].duplicated().sum()

print(f'customer_unique_id_dup: {customer_unique_id_dup}')
print(f'customer_id_dup: {customer_id_dup}')

#  customer_id column contains no duplicate values
#  customer_unique_id column appears to identify repeat customers

customer_unique_id_dup: 3345
customer_id_dup: 0

#### each row represents a customer record associated with an order
- customer_id appears to be unique for each customer record (Primary Key)
- customer_unique_id may represent the actual customer across multiple orders
- No missing values were found

## products table

In [16]:
df_products.sample(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
11105,7151659c0516da0bb3d9f27312efb652,beleza_saude,49.0,1729.0,1.0,2338.0,25.0,23.0,18.0
25182,58249dbd9270974a6a9d8f0222410165,moveis_decoracao,55.0,414.0,1.0,7950.0,52.0,18.0,35.0
23017,b2b748240f8b4fd833d2f61ec84d8ce5,telefonia,59.0,343.0,1.0,150.0,21.0,7.0,14.0
24124,53e4fab5d825e39cb1c18642a71c5f82,cama_mesa_banho,60.0,487.0,4.0,2000.0,45.0,10.0,34.0
17062,3c6be4372f013b15ef6c2d0f89452998,papelaria,59.0,303.0,6.0,5350.0,38.0,30.0,28.0

In [17]:
print(f"shape of products table: {df_products.shape}\n\n")

df_products.info()

print("\n\ncount of null values")
df_products.isnull().sum()

# the product may not have complete information yet

shape of products table: (32951, 9)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB


count of null values

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [ ]:
df_products.duplicated(subset=['product_id']).sum()
# product_id appears to be the Primary Key

np.int64(0)

In [19]:
df_products.describe(include='object')

                              product_id product_category_name
count                              32951                 32341
unique                             32951                    73
top     1e9e8ef04dbcff4541ed26657ea517e5       cama_mesa_banho
freq                                   1                  3029

In [20]:
df_products[['product_name_lenght','product_description_lenght',
             'product_photos_qty','product_weight_g',
             'product_length_cm','product_height_cm',
             'product_width_cm']].agg(['min', 'max'])

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
min,5.0,4.0,1.0,0.0,7.0,2.0,6.0
max,76.0,3992.0,20.0,40425.0,105.0,105.0,118.0

### Initial Observations
- the table contains product attributes
- each row represents a unique product
- table does not contain any foreign keys
- no duplicate values were found in the product_id column
- Several product attributes contain missing values
- Physical dimensions are available for shipping analysis

## sellers table

In [21]:
df_sellers.sample(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
668,04e38a233f726ef161074ab1c9b0399a,1239,sao paulo,SP
1280,101a3a003516bc11253298b2fad3cb65,13503,rio claro,SP
586,d85efbc8eff2b7adf524e2820569adc8,5268,sao paulo,SP
103,99cd94252748d2bdde08e17858233602,12401,sao paulo,SP
3055,198c7ea11960a9844b544d9bcdca860c,37590,jacutinga,MG

In [22]:
print(f"shape of sellers table: {df_sellers.shape}\n\n")

df_sellers.info()

print("\n\ncount of null values")
df_sellers.isnull().sum()

shape of sellers table: (3095, 4)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB


count of null values

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [ ]:
df_sellers.describe(include='object')
# seller_id appears to be the Primary Key (don't hve duplicate seller)

                               seller_id seller_city seller_state
count                               3095        3095         3095
unique                              3095         611           23
top     3442f8959a84dea7ee197c632cb2df15   sao paulo           SP
freq                                   1         694         1849

### Initial Observations
- the table contains seller-related information
- each row represents a unique seller
- the table does not contain any foreign keys
- no duplicate values were found in the seller_id column
- no missing values were found
- seller location information is available for geographic and logistics analysis

## geolocation table