# Data Underastandig

In [2]:
# import libs
import pandas as pd
import numpy as np

In [3]:
# import dataset

df_orders = pd.read_csv('../data/raw/olist_orders_dataset.csv')
df_order_items = pd.read_csv('../data/raw/olist_order_items_dataset.csv')
df_customers = pd.read_csv('../data/raw/olist_customers_dataset.csv')
df_payments = pd.read_csv('../data/raw/olist_order_payments_dataset.csv')
df_products = pd.read_csv('../data/raw/olist_products_dataset.csv')
df_translation = pd.read_csv('../data/raw/product_category_name_translation.csv')
df_geolocation = pd.read_csv('../data/raw/olist_geolocation_dataset.csv')
df_reviews = pd.read_csv('../data/raw/olist_order_reviews_dataset.csv')
df_sellers = pd.read_csv('../data/raw/olist_sellers_dataset.csv')

## orders table

In [4]:
df_orders.sample(n=5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
13759,30c03e784f1c82b58bdbdf321132067f,e1892c28d1493eb6be3661e8daea168f,shipped,2017-07-16 14:44:13,2017-07-16 14:55:07,2017-07-20 18:03:13,NaN,2017-08-08 00:00:00
21544,6005e16820f20784bf25d26f7a60af40,e7203c42cef55542c2c6da43712fad68,delivered,2018-08-02 13:30:59,2018-08-04 04:10:16,2018-08-09 12:18:00,2018-08-10 15:11:46,2018-08-10 00:00:00
85272,3298e7053c95993e6eb284ef3d254b49,62284ba2057b775c15b0abe3c6db005d,delivered,2018-08-20 14:51:27,2018-08-20 16:31:45,2018-08-23 11:04:00,2018-08-30 12:48:38,2018-09-13 00:00:00
45857,c1e0ca05590ed1c16d7aaa4c96fdced6,93bb6b87c2f3b43b991f2b37da6f2095,delivered,2018-03-03 10:03:41,2018-03-06 04:20:29,2018-03-06 22:39:01,2018-04-16 15:18:32,2018-03-29 00:00:00
48052,e434f79ea884de16e5a8bf32afee5333,267f68f411fa32169472fa9b169a7238,delivered,2018-08-02 12:06:40,2018-08-02 13:05:17,2018-08-09 14:21:00,2018-08-16 16:37:47,2018-08-23 00:00:00

In [5]:
df_orders.info()

print("\ncolumns 5 to 7 are date but thire Dtype is Object. should be change in EDA\n")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

columns 5 to 7 are date but thire Dtype is Object. should be change in EDA

In [6]:
print(df_orders.isnull().sum())

print("\n\ncolumns\norder_approved_at\n" \
      "order_delivered_carrier_date\n" \
      "order_delivered_customer_date\n" \
      "have missing value, Missing values may represent orders that have not yet reached that stage")

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64


columns
order_approved_at
order_delivered_carrier_date
order_delivered_customer_date
have missing value, Missing values may represent orders that have not yet reached that stage

In [ ]:
# each order is registered only once
orders_dup = df_orders.order_id.duplicated().sum()
print(f"\nnum of orders_id duplicated: {orders_dup}\n\
    order id don't have null or duplicated value and based on a dataset logical is Primary Key")

# # This customer ID is not duplicated because it creates a new customer ID with each order
customer_dup = df_orders.customer_id.duplicated().sum()
print(f"\nnum of customer id duplicated: {customer_dup}\n")

order_counts = df_orders['order_status'].value_counts()
print(order_counts)

num of orders_id duplicated: 0
    order id don't have null or duplicated value and based on a dataset logical is Primary Key

num of customer id duplicated: 0

order_status
delivered       96478
shipped          1107
canceled          625
unavailable       609
invoiced          314
processing        301
created             5
approved            2
Name: count, dtype: int64

## order_items table

In [8]:
df_order_items.sample(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
64967,9476b4b16d22b40903f24895e4038590,1,363218ba55c610b750224f90bdd34be1,33a6f4b1e7cdc205511e76ba1b6e0186,2018-08-09 00:05:33,74.99,18.33
72581,a5844c6ba1c0c2464b56dc6fa879b9bd,2,04433a8021475a2002663f94203c88da,750303a20e9c56b2a6bc45cdce0b897d,2018-05-02 20:35:15,45.90,7.71
50008,71a9b0571a7e3a1094faefdd6be2a999,1,2d760d94cb67db3551e9a01ceb060161,7c9130f5f3729edd32aa059141d92484,2018-08-31 11:46:03,31.50,19.41
42606,61091d227e531114d8759b1372ba1d48,1,c1f5307decb89342351bec53668cffd9,ea8482cd71df3c1969d7b9473ff13abc,2018-01-31 15:31:46,29.99,11.85
32563,49d0ecc62e79de0f34766cb97df47cf7,1,54bd78d9fbadca90785bae236a7fef2e,8b321bb669392f5163d04c59e235e066,2018-06-12 09:11:49,9.90,12.79

In [9]:
df_order_items.info()

print("\ncolumn shipping_limit_date is date type but  Dtype is Object")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

column shipping_limit_date is date type but  Dtype is Object

In [10]:
# don't exist null values in order items
print(df_order_items.isnull().sum())

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [11]:
df_order_items[['freight_value', 'price']].agg(['min', 'max'])

# Some order items have a freight_value of 0.0. This should be 
# investigated during the EDA phase to determine whether
# it represents free shipping, promotional offers, or another rule ?

     freight_value    price
min           0.00     0.85
max         409.68  6735.00

## customers table

In [12]:
df_customers.sample(5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
76022,3dcab09df0adbfd87b7b49acae4d0a38,bd09840aa5298e8aba03ec8651e60cba,68682,quatro bocas,PA
86028,e63dfa0de407a934f97118509d0a3924,61386166bd766432d31e37d97201eba4,17700,osvaldo cruz,SP
71881,9b9cd22762b75ac6f5cb702eb7c7f758,467c8269886e9c67ab2ec1d5ea86d9f4,2415,sao paulo,SP
86774,e182e74f04b76814710d43aa2fe4c99b,fa40c0a4f499e921d803b074b2ccb688,30510,belo horizonte,MG
79983,7e20bf5ca92da68200643bda76c504c6,576ea0cab426cd8a00fad9a9c90a4494,41213,salvador,BA

In [18]:
df_customers.info()

print("\ncount of null values")
print(df_customers.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

count of null values
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [ ]:
df_customers.describe(include='object')

,customer_id,customer_unique_id,customer_city,customer_state
count,99441,99441,99441,99441
unique,99441,96096,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,sao paulo,SP
freq,1,17,15540,41746

In [ ]:
customer_unique_id_dup = df_customers['customer_unique_id'].duplicated().sum()
customer_id_dup = df_customers['customer_id'].duplicated().sum()

print(f'customer_unique_id_dup: {customer_unique_id_dup}')
print(f'customer_id_dup: {customer_id_dup}')

#  customer_id column contains no duplicate values
#  customer_unique_id column appears to identify repeat customers

customer_unique_id_dup: 3345
customer_id_dup: 0

#### each row represents a customer record associated with an order
- customer_id appears to be unique for each customer record (Primary Key)
- customer_unique_id may represent the actual customer across multiple orders
- No missing values were found

## products table

In [34]:
df_products.sample(5)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
12889,3d9a059cad84dedd0c4cdec92570bf52,beleza_saude,51.0,392.0,1.0,1250.0,30.0,12.0,16.0
25365,44b63b148b673cb9a06672f06683b9b4,cama_mesa_banho,40.0,384.0,1.0,2555.0,55.0,17.0,48.0
25995,93d8b11d613a563f5a26212282bb145e,moveis_decoracao,60.0,1629.0,1.0,400.0,16.0,2.0,11.0
27023,faa51d5c696ac870bc1ec1c6d3691c15,automotivo,54.0,223.0,1.0,1650.0,41.0,19.0,41.0
31460,c85df3adf4b059fd3292eb6530c9a598,esporte_lazer,29.0,282.0,1.0,300.0,20.0,6.0,13.0

In [ ]:
print(f"shape of products table: {df_products.shape}\n\n")

df_products.info()

print("\n\ncount of null values")
df_products.isnull().sum()

# the product may not have complete information yet

shape of products table: (32951, 9)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB


count of null values

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [43]:
df_products.duplicated(subset=['product_id']).sum()

np.int64(0)

In [51]:
df_products.describe(include='object')

                              product_id product_category_name
count                              32951                 32341
unique                             32951                    73
top     1e9e8ef04dbcff4541ed26657ea517e5       cama_mesa_banho
freq                                   1                  3029

In [59]:
df_products[['product_name_lenght','product_description_lenght',
             'product_photos_qty','product_weight_g',
             'product_length_cm','product_height_cm',
             'product_width_cm']].agg(['min', 'max'])

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
min,5.0,4.0,1.0,0.0,7.0,2.0,6.0
max,76.0,3992.0,20.0,40425.0,105.0,105.0,118.0

### Initial Observations
- the table represent products attributes
- each row represent product name and physical dimensions
- don't have forign key 
- No duplicate product_id values ​​found (may Primary Key)
- Several product attributes contain missing values
- Physical dimensions are available for shipping analysis