# KPI_Design

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [9]:
date_cols = ['order_purchase_timestamp', 'order_approved_at',
             'order_delivered_carrier_date', 'order_delivered_customer_date',
             'order_estimated_delivery_date']

order_items_date_columns = ['shipping_limit_date']

orders_master = pd.read_csv('../data/processed/orders_master.csv', parse_dates=date_cols)
items_master = pd.read_csv('../data/processed/items_master.csv', parse_dates=order_items_date_columns)

print(orders_master.shape)
print(items_master.shape)

(99441, 23)
(112650, 19)

In [4]:
orders_master.sample(3)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_to_approved_hours,approval_to_carrier_hours,carrier_to_customer_hours,purchase_to_customer_hours,purchase_to_estimated_hours,has_invalid_duration,delay_vs_estimate_days,is_late,is_on_time,n_items,total_item_price,total_freight_value,avg_distance_km,total_weight_g,review_score
52441,93042fe5b79e4daa53ad9d1b34bd6c15,d30eeb00f2d7a934a10d266391fa54f7,delivered,2018-07-09 22:31:06,2018-07-09 22:45:12,2018-07-10 15:30:00,2018-07-12 23:51:43,2018-07-19,0.235000,16.746667,56.361944,73.343611,217.481667,False,-7.0,False,True,1.0,48.49,9.09,23.578233,717.0,5.0
76593,41e327a61eeb27d89afc2b2f39caad7e,97c33ea3a30e236b2a2e514dadfa171b,delivered,2018-03-09 19:28:24,2018-03-09 19:48:23,2018-03-13 00:56:29,2018-03-21 20:56:25,2018-03-28,0.333056,77.135000,211.998889,289.466944,436.526667,False,-7.0,False,True,1.0,18.80,18.23,822.838640,250.0,5.0
43284,eb9c386367b06468eb9334ad5a9f28bc,f0f6f2b6ed7fefbc460e7e216139a1b0,delivered,2018-04-22 01:27:23,2018-04-24 19:08:47,2018-04-24 16:10:04,2018-04-25 17:06:35,2018-05-10,65.690000,-2.978611,24.941944,87.653333,430.543611,True,-15.0,False,True,1.0,199.90,14.87,152.267977,2800.0,5.0

In [11]:
items_master.sample(3)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name_english,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_photos_qty,product_description_lenght,volume_cm3,freight_ratio,distance_km,is_late,review_score
40521,5c455e9a6d56d30c1652aea99d744e5c,2,a35a9f46dcee0a67c8c7ad8493eb4135,85d9eb9ddc5d00ca9336a2219c97bb13,2018-06-01 11:52:30,25.52,5.26,computers_accessories,200.0,41.0,2.0,29.0,2.0,1084.0,2378.0,0.206113,847.152171,False,2.0
64593,93964a297e76080736d065295fd5b437,1,3dd2a17168ec895c781a9191c1e95ad7,de722cd6dad950a92b7d4f82673f8833,2018-05-16 09:48:27,149.90,13.34,computers_accessories,533.0,22.0,11.0,20.0,1.0,894.0,4840.0,0.088993,2147.107252,False,2.0
80343,b6cc0551cb569413dd9b470a5d485bf1,1,3fc18e3aefe7b9346bd15de863fa0365,53e4c6e0f4312d4d2107a8c9cddf45cd,2017-10-30 13:49:23,71.00,16.13,housewares,2850.0,30.0,30.0,30.0,1.0,808.0,27000.0,0.227183,217.580024,False,5.0

In [6]:
# Total Orders 
total_orders = orders_master['order_id'].nunique()
total_orders

99441

In [12]:
# Total Items Sold 
total_items_sold = items_master.shape[0]
total_items_sold

112650

In [ ]:
# Total Sales
total_sales = orders_master['total_item_price'].sum()
total_sales

np.float64(13591643.7)

In [ ]:
# AOV (Avrage Order Vales)
AVO = orders_master['total_item_price'].mean()
AVO

86.9

In [ ]:
# Total Cosumers
total_customers =

In [ ]:
# Avrage Delivery Time 

deliverd_orders = orders_master[orders_master['order_status'] == 'delivered']
avrage_delivery_time = deliverd_orders['delay_vs_estimate_days'].mean()
avrage_delivery_time

np.float64(-11.875888877371203)

In [ ]:
# On-Time Delivery Rate
on_time = orders_master["delay_vs_estimate_days"] <= 0

on_time_rate = on_time.mean() * 100

on_time_rate

np.float64(90.44659647429128)

In [20]:
# Average Review Score
review_score = items_master['review_score'].mean()
review_score

np.float64(4.0325849536291045)

In [21]:
low_rating_rate = (
    items_master["review_score"].le(2).mean() * 100
)

low_rating_rate

np.float64(15.968930315135374)