# Data Undrastandig

In [2]:
# import libs
import pandas as pd
import numpy as np

In [3]:
# import dataset

df_orders = pd.read_csv('../data/raw/olist_orders_dataset.csv')
df_order_items = pd.read_csv('../data/raw/olist_order_items_dataset.csv')
df_customers = pd.read_csv('../data/raw/olist_customers_dataset.csv')
df_payments = pd.read_csv('../data/raw/olist_order_payments_dataset.csv')
df_products = pd.read_csv('../data/raw/olist_products_dataset.csv')
df_translation = pd.read_csv('../data/raw/product_category_name_translation.csv')
df_geolocation = pd.read_csv('../data/raw/olist_geolocation_dataset.csv')
df_reviews = pd.read_csv('../data/raw/olist_order_reviews_dataset.csv')
df_sellers = pd.read_csv('../data/raw/olist_sellers_dataset.csv')

## orders column

In [44]:
df_orders.sample(n=5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
94642,11f561d4e8e6398b03a193ff522d5a27,f647340bfd59cd852f1edf2b3eba6bbe,delivered,2017-02-16 09:35:34,2017-02-16 09:45:18,2017-02-21 14:44:01,2017-02-24 09:02:57,2017-03-17 00:00:00
27481,95d7f1d6526fe255c28b15b749634392,d08536d91bf5c2d30506a57f29b4452b,delivered,2017-03-20 20:34:03,2017-03-20 20:34:03,2017-03-22 09:04:52,2017-03-24 16:05:27,2017-04-07 00:00:00
25807,71d3e09a5dd729c9a0d368cd5fc9e47c,05fdac815ea6a7f430e1dde5c80bd6c4,delivered,2018-05-04 15:20:52,2018-05-04 15:35:13,2018-05-09 15:13:00,2018-05-14 17:46:51,2018-05-22 00:00:00
73905,681dfff7b99a142f8add974aa7deab83,98884ec6bda9bc1b3104526bbcc19d17,delivered,2018-07-24 18:56:30,2018-07-24 19:05:15,2018-07-27 12:50:00,2018-08-04 00:47:25,2018-08-20 00:00:00
64581,845faa625ef6a2b4549edd96a4bb7308,ae896d8d9bdde52715f81bd2a79fe218,delivered,2018-08-04 20:07:22,2018-08-04 20:24:13,2018-08-06 11:11:00,2018-08-15 19:09:11,2018-08-27 00:00:00

In [91]:
df_orders.info()

print("\ncolumns 5 to 7 are date but thire Dtype is Object. should be change in EDA\n")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

columns 5 to 7 are date but thire Dtype is Object. should be change in EDA

In [92]:
print(df_orders.isnull().sum())

print("\n\ncolumns\norder_approved_at\n" \
      "order_delivered_carrier_date\n" \
      "order_delivered_customer_date\n" \
      "have missing value, Missing values may represent orders that have not yet reached that stage")

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64


columns
order_approved_at
order_delivered_carrier_date
order_delivered_customer_date
have missing value, Missing values may represent orders that have not yet reached that stage

In [56]:
# each order is registered only once
orders_dup = df_orders.order_id.duplicated().sum()
print(f"\nnum of orders_id duplicated: {orders_dup}\n\
    order id don't have null or duplicated value and based on a dataset logical is Primary Key")

# # This customer ID is not duplicated because it creates a new customer ID with each order
customer_dup = df_orders.customer_id.duplicated().sum()
print(f"\nnum of customer id duplicated: {customer_dup}\n")

order_counts = df_orders['order_status'].value_counts()
print(order_counts)

num of orders_id duplicated: 0
    order id don't have null or duplicated value and based on a dataset logical is Primary Key

num of customer id duplicated: 0

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

## order_items column

In [60]:
df_order_items.sample(5)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
16104,24c087010167127767add9f02f8b2019,1,16cc7a098d176187b6d8e9519fa81585,5656537e588803a555b8eb41f07a944b,2018-03-23 00:15:37,64.89,22.16
64977,947bb98f6734ec8fdb3b0a222f19c454,1,cf8316c961640d38321241895b7811c2,da8622b14eb17ae2831f4ac5b9dab84a,2018-05-07 18:15:17,129.90,16.44
5921,0d6bfb2c384abf1053a600d79eb2dcfd,1,4b456247c6fd6370f0c01903b0c6d67d,87142160b41353c4e5fca2360caf6f92,2017-03-30 21:55:12,139.90,17.82
88328,c893d855b41d9ebc443d3addef1755b0,1,e53e557d5a159f5aa2c5e995dfdf244b,88460e8ebdecbfecb5f9601833981930,2018-03-08 13:09:20,76.25,16.97
13018,1d8c9526428c9c7c72e2e5f4b8d43edf,1,9c7da616e5b3dd8100858b72e883b7a8,dc4a0fc896dc34b0d5bfec8438291c80,2018-05-30 00:56:11,44.90,12.79

In [77]:
df_order_items.info()

print("\ncolumn shipping_limit_date is date type but  Dtype is Object")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

column shipping_limit_date is date type but  Dtype is Object

In [ ]:
# don't exist null values in order items
print(df_order_items.isnull().sum())

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [ ]:
df_order_items[['freight_value', 'price']].agg(['min', 'max'])

# why freight_value have 0.0 value ?

     freight_value    price
min           0.00     0.85
max         409.68  6735.00

In [102]:
sellers_per_order = df_order_items.groupby('order_id')['seller_id'].nunique()
multi_seller_orders = (sellers_per_order > 1).sum()
print(f"تعداد سفارشاتی که شامل چند فروشنده مختلف هستند: {multi_seller_orders:,}")

تعداد سفارشاتی که شامل چند فروشنده مختلف هستند: 1,278

In [103]:
# محاسبه تعداد آیتم‌های هر سفارش
items_per_order = df_order_items.groupby('order_id')['order_item_id'].max()

print(f"میانگین تعداد آیتم در هر سفارش: {items_per_order.mean():.2f}")
print(f"حداکثر تعداد آیتم در یک سفارش: {items_per_order.max()}")

میانگین تعداد آیتم در هر سفارش: 1.14
حداکثر تعداد آیتم در یک سفارش: 21